export const OUTDOOR_HOBBIES = [
  "Airsoft",
  "Archery",
  "Association football",
  "Australian rules football",
  "Auto racing",
  "Baseball",
  "Beach volleyball",
  "Breakdancing",
  "Capoeira",
  "Climbing",
  "Cornhole",
  "Cricket",
  "Croquet",
  "Cycling",
  "Disc golf",
  "Dog sport",
  "Equestrianism",
  "Exhibition drill",
  "Field hockey",
  "Figure skating",
  "Fishing",
  "Fitness",
  "Footbag",
  "Frisbee",
  "Golfing",
  "Handball",
  "Horseback riding",
  "Horsemanship",
  "Horseshoes",
  "Iceboat racing",
  "Jukskei",
  "Kart racing[",
  "Knife throwing",
  "Lacrosse",
  "Longboarding",
  "Long-distance running",
  "Marching band",
  "Mini golf",
  "Model aircraft",
  "Orienteering",
  "Pickleball",
  "Powerboat racing",
  "Quidditch",
  "Race walking",
  "Racquetball",
  "Radio-controlled car racing",
  "Radio-controlled model playing",
  "Roller derby[215]",
  "Rugby league football",
  "Sculling or rowing",
  "Shooting sports",
  "Skateboarding",
  "Skiing",
  "Sled dog racing",
  "Softball",
  "Speed skating",
  "Squash",
  "Surfing",
  "Swimming",
  "Table tennis",
  "Tennis[219]",
  "Tennis polo",
  "Tether car",
  "Tour skating",
  "Tourism",
  "Trapshooting",
  "Triathlon",
  "Ultimate frisbee",
  "Volleyball",
  "Water polo",
];
